spring:
  application:
    name: ASSIGNMENT-ORDER



  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ordercustomer
    username: postgres
    password: postgress

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
