spring:
  application:
    name: QUIZ-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/questionbank
    username: postgres
    password: postgress
 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port:9010
